# fly.toml app configuration file generated for turn-classic on 2025-03-12T23:33:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'turn-classic'
primary_region = 'yyz'

[build]

[env]
  PORT = '8080'

[processes]
  app = 'run --allow-net --allow-read --allow-write --allow-env --allow-ffi --unstable --node-modules-dir server.ts'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
